insert into tbl_players (pl_creation_date, pl_last_update_date, pl_name, pl_id) values (TIMESTAMP '2022-05-17 20:58:02', TIMESTAMP '2022-05-17 20:58:02', 'Eric', NEXTVAL('seq_player'));
insert into tbl_players (pl_creation_date, pl_last_update_date, pl_name, pl_id) values (TIMESTAMP '2022-05-17 20:58:02', TIMESTAMP '2022-05-17 20:58:02', 'Marianne', NEXTVAL('seq_player'));
insert into tbl_players (pl_creation_date, pl_last_update_date, pl_name, pl_id) values (TIMESTAMP '2022-05-17 20:58:02', TIMESTAMP '2022-05-17 20:58:02', 'Stéphane', NEXTVAL('seq_player'));
insert into tbl_players (pl_creation_date, pl_last_update_date, pl_name, pl_id) values (TIMESTAMP '2022-05-17 20:58:02', TIMESTAMP '2022-05-17 20:58:02', 'Gilliane', NEXTVAL('seq_player'));
insert into tbl_players (pl_creation_date, pl_last_update_date, pl_name, pl_id) values (TIMESTAMP '2022-05-17 20:58:02', TIMESTAMP '2022-05-17 20:58:02', 'Lionel', NEXTVAL('seq_player'));
insert into tbl_players (pl_creation_date, pl_last_update_date, pl_name, pl_id) values (TIMESTAMP '2022-05-17 20:58:02', TIMESTAMP '2022-05-17 20:58:02', 'Bernard', NEXTVAL('seq_player'));

insert into tbl_roles (rol_creation_date, rol_last_update_date, rol_name, rol_id) values (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', 'Annonceur', NEXTVAL('seq_role'));
insert into tbl_roles (rol_creation_date, rol_last_update_date, rol_name, rol_id) values (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', 'Annonceur 1', NEXTVAL('seq_role'));
insert into tbl_roles (rol_creation_date, rol_last_update_date, rol_name, rol_id) values (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', 'Annonceur 2', NEXTVAL('seq_role'));
insert into tbl_roles (rol_creation_date, rol_last_update_date, rol_name, rol_id) values (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', 'Adversaire 1', NEXTVAL('seq_role'));
insert into tbl_roles (rol_creation_date, rol_last_update_date, rol_name, rol_id) values (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', 'Adversaire 2', NEXTVAL('seq_role'));
insert into tbl_roles (rol_creation_date, rol_last_update_date, rol_name, rol_id) values (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', 'Adversaire 3', NEXTVAL('seq_role'));
insert into tbl_roles (rol_creation_date, rol_last_update_date, rol_name, rol_id) values (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', 'Adversaire 4', NEXTVAL('seq_role'));
insert into tbl_roles (rol_creation_date, rol_last_update_date, rol_name, rol_id) values (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', 'Mort', NEXTVAL('seq_role'));

insert into tbl_contracts (ctr_creation_date, ctr_last_update_date, ctr_name, ctr_number_players, ctr_id) VALUES (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', 'Emballage 8', 4, NEXTVAL('seq_contract'));
insert into tbl_contracts (ctr_creation_date, ctr_last_update_date, ctr_name, ctr_number_players, ctr_id) VALUES (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', 'Emballage 9', 4, NEXTVAL('seq_contract'));
insert into tbl_contracts (ctr_creation_date, ctr_last_update_date, ctr_name, ctr_number_players, ctr_id) VALUES (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', 'Emballage 10', 4, NEXTVAL('seq_contract'));
insert into tbl_contracts (ctr_creation_date, ctr_last_update_date, ctr_name, ctr_number_players, ctr_id) VALUES (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', 'Emballage 11', 4, NEXTVAL('seq_contract'));
insert into tbl_contracts (ctr_creation_date, ctr_last_update_date, ctr_name, ctr_number_players, ctr_id) VALUES (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', 'Emballage 12', 4, NEXTVAL('seq_contract'));
insert into tbl_contracts (ctr_creation_date, ctr_last_update_date, ctr_name, ctr_number_players, ctr_id) VALUES (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', 'Emballage 13', 4, NEXTVAL('seq_contract'));
insert into tbl_contracts (ctr_creation_date, ctr_last_update_date, ctr_name, ctr_number_players, ctr_id) VALUES (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', '6 seul', 4, NEXTVAL('seq_contract'));
insert into tbl_contracts (ctr_creation_date, ctr_last_update_date, ctr_name, ctr_number_players, ctr_id) VALUES (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', '7 seul', 4, NEXTVAL('seq_contract'));
insert into tbl_contracts (ctr_creation_date, ctr_last_update_date, ctr_name, ctr_number_players, ctr_id) VALUES (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', '8 seul', 4, NEXTVAL('seq_contract'));
insert into tbl_contracts (ctr_creation_date, ctr_last_update_date, ctr_name, ctr_number_players, ctr_id) VALUES (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', 'Trou', 4, NEXTVAL('seq_contract'));
insert into tbl_contracts (ctr_creation_date, ctr_last_update_date, ctr_name, ctr_number_players, ctr_id) VALUES (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', 'Petite misère (SEUL)', 4, NEXTVAL('seq_contract'));
insert into tbl_contracts (ctr_creation_date, ctr_last_update_date, ctr_name, ctr_number_players, ctr_id) VALUES (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', 'Petite misère (A DEUX)', 4, NEXTVAL('seq_contract'));
insert into tbl_contracts (ctr_creation_date, ctr_last_update_date, ctr_name, ctr_number_players, ctr_id) VALUES (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', '8 plis sur petite misère', 4, NEXTVAL('seq_contract'));
insert into tbl_contracts (ctr_creation_date, ctr_last_update_date, ctr_name, ctr_number_players, ctr_id) VALUES (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', 'Abondance', 4, NEXTVAL('seq_contract'));
insert into tbl_contracts (ctr_creation_date, ctr_last_update_date, ctr_name, ctr_number_players, ctr_id) VALUES (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', 'Grande misère (SEUL)', 4, NEXTVAL('seq_contract'));
insert into tbl_contracts (ctr_creation_date, ctr_last_update_date, ctr_name, ctr_number_players, ctr_id) VALUES (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', 'Grande Misère (A DEUX)', 4, NEXTVAL('seq_contract'));
insert into tbl_contracts (ctr_creation_date, ctr_last_update_date, ctr_name, ctr_number_players, ctr_id) VALUES (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', 'Grande misère sur trou (SEUL)', 4, NEXTVAL('seq_contract'));
insert into tbl_contracts (ctr_creation_date, ctr_last_update_date, ctr_name, ctr_number_players, ctr_id) VALUES (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', 'Grande Misère sur trou (A DEUX)', 4, NEXTVAL('seq_contract'));
insert into tbl_contracts (ctr_creation_date, ctr_last_update_date, ctr_name, ctr_number_players, ctr_id) VALUES (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', 'Grande misère sur table (SEUL)', 4, NEXTVAL('seq_contract'));
insert into tbl_contracts (ctr_creation_date, ctr_last_update_date, ctr_name, ctr_number_players, ctr_id) VALUES (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', 'Grande Misère sur table (A DEUX)', 4, NEXTVAL('seq_contract'));
insert into tbl_contracts (ctr_creation_date, ctr_last_update_date, ctr_name, ctr_number_players, ctr_id) VALUES (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', 'Grande misère sur trou et sur table', 4, NEXTVAL('seq_contract'));
insert into tbl_contracts (ctr_creation_date, ctr_last_update_date, ctr_name, ctr_number_players, ctr_id) VALUES (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', 'Solo schelem', 4, NEXTVAL('seq_contract'));
insert into tbl_contracts (ctr_creation_date, ctr_last_update_date, ctr_name, ctr_number_players, ctr_id) VALUES (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', 'Emballage 8', 5, NEXTVAL('seq_contract'));
insert into tbl_contracts (ctr_creation_date, ctr_last_update_date, ctr_name, ctr_number_players, ctr_id) VALUES (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', 'Emballage 9', 5, NEXTVAL('seq_contract'));
insert into tbl_contracts (ctr_creation_date, ctr_last_update_date, ctr_name, ctr_number_players, ctr_id) VALUES (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', 'Emballage 10', 5, NEXTVAL('seq_contract'));
insert into tbl_contracts (ctr_creation_date, ctr_last_update_date, ctr_name, ctr_number_players, ctr_id) VALUES (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', 'Emballage 11', 5, NEXTVAL('seq_contract'));
insert into tbl_contracts (ctr_creation_date, ctr_last_update_date, ctr_name, ctr_number_players, ctr_id) VALUES (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', 'Emballage 12', 5, NEXTVAL('seq_contract'));
insert into tbl_contracts (ctr_creation_date, ctr_last_update_date, ctr_name, ctr_number_players, ctr_id) VALUES (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', 'Emballage 13', 5, NEXTVAL('seq_contract'));
insert into tbl_contracts (ctr_creation_date, ctr_last_update_date, ctr_name, ctr_number_players, ctr_id) VALUES (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', '6 seul', 5, NEXTVAL('seq_contract'));
insert into tbl_contracts (ctr_creation_date, ctr_last_update_date, ctr_name, ctr_number_players, ctr_id) VALUES (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', '7 seul', 5, NEXTVAL('seq_contract'));
insert into tbl_contracts (ctr_creation_date, ctr_last_update_date, ctr_name, ctr_number_players, ctr_id) VALUES (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', '8 seul', 5, NEXTVAL('seq_contract'));
insert into tbl_contracts (ctr_creation_date, ctr_last_update_date, ctr_name, ctr_number_players, ctr_id) VALUES (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', 'Trou', 5, NEXTVAL('seq_contract'));
insert into tbl_contracts (ctr_creation_date, ctr_last_update_date, ctr_name, ctr_number_players, ctr_id) VALUES (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', 'Petite misère (SEUL)', 5, NEXTVAL('seq_contract'));
insert into tbl_contracts (ctr_creation_date, ctr_last_update_date, ctr_name, ctr_number_players, ctr_id) VALUES (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', 'Petite misère (A DEUX)', 5, NEXTVAL('seq_contract'));
insert into tbl_contracts (ctr_creation_date, ctr_last_update_date, ctr_name, ctr_number_players, ctr_id) VALUES (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', '8 plis sur petite misère', 5, NEXTVAL('seq_contract'));
insert into tbl_contracts (ctr_creation_date, ctr_last_update_date, ctr_name, ctr_number_players, ctr_id) VALUES (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', 'Abondance', 5, NEXTVAL('seq_contract'));
insert into tbl_contracts (ctr_creation_date, ctr_last_update_date, ctr_name, ctr_number_players, ctr_id) VALUES (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', 'Grande misère (SEUL)', 5, NEXTVAL('seq_contract'));
insert into tbl_contracts (ctr_creation_date, ctr_last_update_date, ctr_name, ctr_number_players, ctr_id) VALUES (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', 'Grande Misère (A DEUX)', 5, NEXTVAL('seq_contract'));
insert into tbl_contracts (ctr_creation_date, ctr_last_update_date, ctr_name, ctr_number_players, ctr_id) VALUES (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', 'Grande misère sur trou (SEUL)', 5, NEXTVAL('seq_contract'));
insert into tbl_contracts (ctr_creation_date, ctr_last_update_date, ctr_name, ctr_number_players, ctr_id) VALUES (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', 'Grande Misère sur trou (A DEUX)', 5, NEXTVAL('seq_contract'));
insert into tbl_contracts (ctr_creation_date, ctr_last_update_date, ctr_name, ctr_number_players, ctr_id) VALUES (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', 'Grande misère sur table (SEUL)', 5, NEXTVAL('seq_contract'));
insert into tbl_contracts (ctr_creation_date, ctr_last_update_date, ctr_name, ctr_number_players, ctr_id) VALUES (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', 'Grande Misère sur table (A DEUX)', 5, NEXTVAL('seq_contract'));
insert into tbl_contracts (ctr_creation_date, ctr_last_update_date, ctr_name, ctr_number_players, ctr_id) VALUES (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', 'Grande misère sur trou et sur table', 5, NEXTVAL('seq_contract'));
insert into tbl_contracts (ctr_creation_date, ctr_last_update_date, ctr_name, ctr_number_players, ctr_id) VALUES (TIMESTAMP '2022-05-17 20:59:02', TIMESTAMP '2022-05-17 20:59:02', 'Solo schelem', 5, NEXTVAL('seq_contract'));

insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(1, 2);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(1, 3);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(1, 4);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(1, 5);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(2, 2);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(2, 3);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(2, 4);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(2, 5);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(3, 2);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(3, 3);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(3, 4);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(3, 5);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(4, 2);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(4, 3);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(4, 4);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(4, 5);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(5, 2);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(5, 3);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(5, 4);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(5, 5);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(6, 2);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(6, 3);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(6, 4);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(6, 5);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(7, 1);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(7, 4);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(7, 5);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(7, 6);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(8, 1);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(8, 4);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(8, 5);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(8, 6);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(9, 1);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(9, 4);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(9, 5);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(9, 6);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(10, 2);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(10, 3);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(10, 4);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(10, 5);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(11, 1);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(11, 4);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(11, 5);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(11, 6);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(12, 2);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(12, 3);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(12, 4);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(12, 5);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(13, 1);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(13, 4);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(13, 5);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(13, 6);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(14, 1);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(14, 4);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(14, 5);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(14, 6);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(15, 1);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(15, 4);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(15, 5);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(15, 6);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(16, 2);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(16, 3);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(16, 4);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(16, 5);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(17, 2);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(17, 3);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(17, 4);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(17, 5);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(18, 2);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(18, 3);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(18, 4);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(18, 5);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(19, 2);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(19, 3);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(19, 4);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(19, 5);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(20, 2);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(20, 3);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(20, 4);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(20, 5);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(21, 2);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(21, 3);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(21, 4);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(21, 5);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(22, 2);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(22, 3);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(22, 4);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(22, 5);

insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(23, 2);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(23, 3);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(23, 4);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(23, 5);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(23, 8);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(24, 2);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(24, 3);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(24, 4);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(24, 5);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(24, 8);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(25, 2);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(25, 3);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(25, 4);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(25, 5);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(25, 8);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(26, 2);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(26, 3);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(26, 4);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(26, 5);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(26, 8);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(27, 2);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(27, 3);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(27, 4);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(27, 5);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(27, 8);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(28, 2);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(28, 3);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(28, 4);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(28, 5);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(28, 8);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(29, 1);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(29, 4);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(29, 5);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(29, 6);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(29, 8);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(30, 1);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(30, 4);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(30, 5);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(30, 6);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(30, 8);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(31, 1);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(31, 4);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(31, 5);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(31, 6);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(31, 8);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(32, 2);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(32, 3);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(32, 4);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(32, 5);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(32, 8);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(33, 1);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(33, 4);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(33, 5);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(33, 6);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(33, 8);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(34, 2);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(34, 3);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(34, 4);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(34, 5);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(34, 8);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(35, 1);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(35, 4);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(35, 5);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(35, 6);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(35, 8);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(36, 1);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(36, 4);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(36, 5);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(36, 6);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(36, 8);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(37, 1);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(37, 4);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(37, 5);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(37, 6);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(37, 8);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(38, 2);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(38, 3);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(38, 4);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(38, 5);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(38, 8);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(39, 2);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(39, 3);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(39, 4);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(39, 5);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(39, 8);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(40, 2);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(40, 3);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(40, 4);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(40, 5);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(40, 8);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(41, 2);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(41, 3);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(41, 4);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(41, 5);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(41, 8);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(42, 2);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(42, 3);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(42, 4);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(42, 5);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(42, 8);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(43, 2);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(43, 3);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(43, 4);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(43, 5);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(43, 8);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(44, 2);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(44, 3);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(44, 4);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(44, 5);
insert into tbl_contract_roles(cro_ctr_id, cro_rol_id) VALUES(44, 8);